### ISSUE TITLE
Exercise 2 and 3 are missing links to table of contents.

### ISSUE THREAD

**Issue by judyer28** [microsoft/TechExcel-Migrate-Linux-workloads#14]
Table of contents links missing from following exercises:
https://microsoft.github.io/TechExcel-Migrate-Linux-workloads/docs/02_migrate_web_app/02_migrate_web_app.html
https://microsoft.github.io/TechExcel-Migrate-Linux-workloads/docs/03_enable_azure_arc/03_enable_azure_arc.html

**Comment by tiagocostapt** [comment]
@judyer28 fixed for 03: Enable Azure Arc. Please check if all is good on your side.

**Comment by judyer28** [comment]
@tiagocostapt I can confirm Arc section looks fixed.

**Comment by tiagocostapt** [comment]
Exercise 02 is fixed.
