### ISSUE TITLE
Connection not successful "Error: DNSResolution"

### ISSUE THREAD

**Issue by judyer28** [microsoft/TechExcel-Migrate-Linux-workloads#17]
Connection not successful in step 4.  [Deploy and configure Azure Firewall | Migrate Linux workloads to Azure (microsoft.github.io)](https://microsoft.github.io/TechExcel-Migrate-Linux-workloads/docs/04_secure_your_workloads/04_05.html)

I think there is a DNS misconfiguration.  If I do connectivity test on IP 204.79.197.200 it works ok.  With FQDN I get Local Error: DNSResolution.

**Comment by HeyMo0sh** [comment]
@tiagocostapt  can you look at this please

**Comment by HeyMo0sh** [comment]
I do not get a FQDN error when I tried:


<img width="1270" alt="image" src="https://github.com/microsoft/TechExcel-Migrate-Linux-workloads/assets/30678414/c1bd2a76-0b17-45c1-94d9-c9ccafc9cd6b">

<img width="1252" alt="image" src="https://github.com/microsoft/TechExcel-Migrate-Linux-workloads/assets/30678414/7c32f0f1-3871-4896-902b-008389616410">

**Comment by tiagocostapt** [comment]
@HeyMo0sh I ran the lab twice and also didn't get it. I was trying to understand why @judyer28 got that, but I can't figure it out.
@judyer28 can you check again?

**Comment by judyer28** [comment]
@tiagocostapt @HeyMo0sh I am troubleshooting this now.  One potential issue I see is the Network Watcher Agent does not support RHEL 9.3.  https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/network-watcher-linux?tabs=powershell#supported-operating-systems.  Not sure if this is related as the extension seems to have installed ok.  Will keep troubleshooting.
